apply plugin: 'com.android.library'

group = 'expo.modules.swarmnode'
version = '0.7.6'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()

// Simple helper that allows the root project to override versions declared by this library.
ext.safeExtGet = { prop, fallback ->
  rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

dependencies {
  implementation files('libs/mobile.aar')
}

android {
  namespace "expo.modules.swarmnode"
  
  compileSdkVersion safeExtGet("compileSdkVersion", 36)
  
  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 21)
    targetSdkVersion safeExtGet("targetSdkVersion", 36)
    versionCode 1
    versionName "0.7.6"
  }
  
  lintOptions {
    abortOnError false
  }
}
